name: cffconvert

on:
  workflow_dispatch:

jobs:
  generate-codemeta:
    name: "validate and convert CITATION.cff. Open a PR"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install eossr and cffconvert
        run: |
          pip install cffconvert eossr

      - name: Check whether the citation metadata from CITATION.cff is valid
        run: |
          cffconvert --validate --infile CITATION.cff

      - name: Convert CITATION.cff to Codemeta metadata format
        if: success()
        run: |
          cffconvert --infile CITATION.cff --format codemeta --outfile codemeta.json

      - name: Fix codemeta.json
        if: success()
        run: |
          cd dev && python codemeta.py

      - name: Validate codemeta.json
        if: success()
        run: |
          eossr-metadata-validator codemeta.json

      - name: Create new branch
        id: create_branch
        run: |
          BRANCH_NAME=update-codemeta-${{ github.run_id }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b $BRANCH_NAME
          git add codemeta.json
          git commit -m "Update codemeta.json from CITATION.cff"
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update codemeta.json from CITATION.cff
          branch: ${{ steps.create_branch.outputs.branch_name }}
          title: "Update codemeta.json"
          body: |
            This PR updates the codemeta.json file generated from CITATION.cff.
            - Validated `CITATION.cff`
            - Generated and validated `codemeta.json`

